//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_School : DbContext
    {
        public Entities_School()
            : base("name=Entities_School")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<table_act> table_act { get; set; }
        public virtual DbSet<table_activity> table_activity { get; set; }
        public virtual DbSet<table_boarding> table_boarding { get; set; }
        public virtual DbSet<table_c_b> table_c_b { get; set; }
        public virtual DbSet<table_c_b_sum> table_c_b_sum { get; set; }
        public virtual DbSet<table_caretaker> table_caretaker { get; set; }
        public virtual DbSet<table_catalogue> table_catalogue { get; set; }
        public virtual DbSet<table_class> table_class { get; set; }
        public virtual DbSet<table_class_allocation> table_class_allocation { get; set; }
        public virtual DbSet<table_commendation> table_commendation { get; set; }
        public virtual DbSet<table_comment_term> table_comment_term { get; set; }
        public virtual DbSet<table_comment_term_mid> table_comment_term_mid { get; set; }
        public virtual DbSet<table_configuration> table_configuration { get; set; }
        public virtual DbSet<table_default_comment> table_default_comment { get; set; }
        public virtual DbSet<table_exam> table_exam { get; set; }
        public virtual DbSet<table_exam_student> table_exam_student { get; set; }
        public virtual DbSet<table_exam1> table_exam1 { get; set; }
        public virtual DbSet<table_expenditure> table_expenditure { get; set; }
        public virtual DbSet<table_expenditure_list> table_expenditure_list { get; set; }
        public virtual DbSet<table_fees> table_fees { get; set; }
        public virtual DbSet<table_fees_status> table_fees_status { get; set; }
        public virtual DbSet<table_grade_range> table_grade_range { get; set; }
        public virtual DbSet<table_inventory_detail> table_inventory_detail { get; set; }
        public virtual DbSet<table_inventory_summary> table_inventory_summary { get; set; }
        public virtual DbSet<table_mark_range> table_mark_range { get; set; }
        public virtual DbSet<table_p_p1> table_p_p1 { get; set; }
        public virtual DbSet<table_payment_alert> table_payment_alert { get; set; }
        public virtual DbSet<table_payment_analysis> table_payment_analysis { get; set; }
        public virtual DbSet<table_payment_fees> table_payment_fees { get; set; }
        public virtual DbSet<table_payment_fees_detail> table_payment_fees_detail { get; set; }
        public virtual DbSet<table_payment_fees_prac> table_payment_fees_prac { get; set; }
        public virtual DbSet<table_payment_others> table_payment_others { get; set; }
        public virtual DbSet<table_payroll_config> table_payroll_config { get; set; }
        public virtual DbSet<table_payroll_register> table_payroll_register { get; set; }
        public virtual DbSet<table_payroll_salary> table_payroll_salary { get; set; }
        public virtual DbSet<table_pin> table_pin { get; set; }
        public virtual DbSet<table_pin_history> table_pin_history { get; set; }
        public virtual DbSet<table_promotion_range> table_promotion_range { get; set; }
        public virtual DbSet<table_promotion_status> table_promotion_status { get; set; }
        public virtual DbSet<table_punishment> table_punishment { get; set; }
        public virtual DbSet<table_que> table_que { get; set; }
        public virtual DbSet<table_result> table_result { get; set; }
        public virtual DbSet<table_result_cbt> table_result_cbt { get; set; }
        public virtual DbSet<table_result_mid> table_result_mid { get; set; }
        public virtual DbSet<table_result_session> table_result_session { get; set; }
        public virtual DbSet<table_result_test> table_result_test { get; set; }
        public virtual DbSet<table_resumption> table_resumption { get; set; }
        public virtual DbSet<table_resumption_mid> table_resumption_mid { get; set; }
        public virtual DbSet<table_reward> table_reward { get; set; }
        public virtual DbSet<table_schools> table_schools { get; set; }
        public virtual DbSet<table_session> table_session { get; set; }
        public virtual DbSet<table_sms_balance> table_sms_balance { get; set; }
        public virtual DbSet<table_sms_history> table_sms_history { get; set; }
        public virtual DbSet<table_staff> table_staff { get; set; }
        public virtual DbSet<table_student> table_student { get; set; }
        public virtual DbSet<table_student_old> table_student_old { get; set; }
        public virtual DbSet<table_student_user> table_student_user { get; set; }
        public virtual DbSet<table_subject> table_subject { get; set; }
        public virtual DbSet<table_subject_allocation> table_subject_allocation { get; set; }
        public virtual DbSet<table_subject_registration> table_subject_registration { get; set; }
        public virtual DbSet<table_term> table_term { get; set; }
        public virtual DbSet<table_trait> table_trait { get; set; }
        public virtual DbSet<table_trait_mid> table_trait_mid { get; set; }
        public virtual DbSet<table_user> table_user { get; set; }
        public virtual DbSet<table_verify_schoolms> table_verify_schoolms { get; set; }
        public virtual DbSet<table_web> table_web { get; set; }
        public virtual DbSet<table_year> table_year { get; set; }
        public virtual DbSet<table_c_o> table_c_o { get; set; }
        public virtual DbSet<table_sae> table_sae { get; set; }
    }
}
