//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_staff
    {
        public int p_id { get; set; }
        public string Title { get; set; }
        public string Surname { get; set; }
        public string Other_Name { get; set; }
        public string Full_Name { get; set; }
        public string Date { get; set; }
        public string School { get; set; }
        public string Position { get; set; }
        public string Code { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime L_U { get; set; }
    }
}
