//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_student
    {
        public int p_id { get; set; }
        public string Student_ID { get; set; }
        public string Surname { get; set; }
        public string Other_Name { get; set; }
        public string Full_Name { get; set; }
        public string Date_of_Birth { get; set; }
        public string Class { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string Student_Tel { get; set; }
        public string Department { get; set; }
        public string Year_of_Admission { get; set; }
        public string Home_Town { get; set; }
        public string State_of_Origin { get; set; }
        public string Home_Address { get; set; }
        public string Father_Name { get; set; }
        public string Father_Phone { get; set; }
        public string Father_Occupation { get; set; }
        public string Father_Email { get; set; }
        public string Mother_Name { get; set; }
        public string Mother_Phone { get; set; }
        public string Mother_Occupation { get; set; }
        public string Contact_Address { get; set; }
        public string Date { get; set; }
        public string Day { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Religion { get; set; }
        public string Class_Teacher { get; set; }
        public string School { get; set; }
        public string Student_Status { get; set; }
        public string Session { get; set; }
        public string Term { get; set; }
        public string g_name { get; set; }
        public string g_phone { get; set; }
        public string g_occupation { get; set; }
        public string g_email { get; set; }
        public string mother_email { get; set; }
        public string Student_Status1 { get; set; }
        public string Scholarship_Status { get; set; }
        public System.DateTime L_U { get; set; }
    }
}
