//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_payment_alert
    {
        public int p_id { get; set; }
        public string Student_Name { get; set; }
        public string Student_ID { get; set; }
        public string Phone { get; set; }
        public string Amount_Paid { get; set; }
        public string Balance { get; set; }
        public string Day { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
        public string school { get; set; }
        public string Code { get; set; }
        public System.DateTime L_U { get; set; }
    }
}
