//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_verify_schoolms
    {
        public int p_id { get; set; }
        public string School_Name { get; set; }
        public string School_ID { get; set; }
        public string Campus { get; set; }
        public string Pre_id { get; set; }
        public string Key1 { get; set; }
        public string Date { get; set; }
        public string connection_string { get; set; }
        public string Code { get; set; }
        public string Status { get; set; }
        public string s_t { get; set; }
        public System.DateTime L_U { get; set; }
    }
}
