//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_user
    {
        public int p_id { get; set; }
        public string Surname { get; set; }
        public string Other_Name { get; set; }
        public string Full_Name { get; set; }
        public string School { get; set; }
        public string Department { get; set; }
        public string Category_Status { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Registered_By { get; set; }
        public string Date { get; set; }
        public System.DateTime L_U { get; set; }
    }
}
