//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_activity
    {
        public int p_id { get; set; }
        public string Student_ID { get; set; }
        public string Student_Name { get; set; }
        public string Activity { get; set; }
        public string Times { get; set; }
        public string session { get; set; }
        public string term { get; set; }
        public string date { get; set; }
        public string code { get; set; }
        public System.DateTime L_U { get; set; }
    }
}
