//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_schools
    {
        public int p_id { get; set; }
        public string School { get; set; }
        public string Pre_id { get; set; }
        public string School_Name { get; set; }
        public string s_t { get; set; }
        public string S_Status { get; set; }
        public string sub_domain { get; set; }
        public string root { get; set; }
        public string root_p { get; set; }
        public Nullable<System.DateTime> L_U { get; set; }
    }
}
