//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_boarding
    {
        public int p_id { get; set; }
        public decimal Boarding { get; set; }
        public decimal Feeding { get; set; }
        public decimal T_Short { get; set; }
        public decimal T_Long { get; set; }
        public string School { get; set; }
        public string Date { get; set; }
        public System.DateTime L_U { get; set; }
    }
}
