//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_payroll_register
    {
        public int p_id { get; set; }
        public string Staff_Name { get; set; }
        public decimal Actual_Salary { get; set; }
        public decimal Social_Saving { get; set; }
        public decimal Compulsory_Saving { get; set; }
        public decimal Overtime { get; set; }
        public decimal Bonus { get; set; }
        public decimal Tuition_Deduct { get; set; }
        public decimal Loan_Deduct { get; set; }
        public decimal Tax_Deduct { get; set; }
        public string Bank_Name { get; set; }
        public string Bank_Account { get; set; }
        public string Bank_Code { get; set; }
        public string Account_Type { get; set; }
        public string Beneficiary_Name { get; set; }
        public string Currency_Code { get; set; }
        public string School { get; set; }
        public string Date { get; set; }
        public string code { get; set; }
        public System.DateTime L_U { get; set; }
    }
}
