//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_catalogue
    {
        public int p_id { get; set; }
        public string Subject { get; set; }
        public string Class { get; set; }
        public string Author { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string code { get; set; }
        public string date { get; set; }
        public string day { get; set; }
        public string month { get; set; }
        public string year { get; set; }
        public string school { get; set; }
        public System.DateTime L_U { get; set; }
    }
}
