//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_payment_analysis
    {
        public int p_id { get; set; }
        public string s_n { get; set; }
        public string Payment_Description { get; set; }
        public string Teller_No { get; set; }
        public string Payment_Date { get; set; }
        public int Amount_Paid { get; set; }
        public decimal Amount_Left { get; set; }
        public string Code { get; set; }
        public string Student_Id { get; set; }
        public string Session { get; set; }
        public string Term { get; set; }
        public string student_name { get; set; }
        public string school { get; set; }
        public decimal Amount_Due { get; set; }
        public string Receipt_No { get; set; }
        public string Class { get; set; }
        public string Day { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Student_Status1 { get; set; }
        public System.DateTime L_U { get; set; }
    }
}
