//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_trait
    {
        public int p_id { get; set; }
        public string Student_ID { get; set; }
        public string Student_Name { get; set; }
        public string Qualities { get; set; }
        public string Excellent { get; set; }
        public string Good { get; set; }
        public string Fair { get; set; }
        public string Poor { get; set; }
        public string Session { get; set; }
        public string Term { get; set; }
        public string School { get; set; }
        public string Date { get; set; }
        public string Code { get; set; }
        public string Class { get; set; }
        public System.DateTime L_U { get; set; }
    }
}
