//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_comment_term
    {
        public int p_id { get; set; }
        public string Student_ID { get; set; }
        public string Student_Name { get; set; }
        public string Session { get; set; }
        public string Term { get; set; }
        public string Class { get; set; }
        public string Code { get; set; }
        public string Remark_Teacher { get; set; }
        public string Remark_Principal { get; set; }
        public int No_of_time_school_open { get; set; }
        public int No_of_time_student_present { get; set; }
        public string Comment_Punctuality { get; set; }
        public string General_Remark { get; set; }
        public string Note_to_Parent { get; set; }
        public string Concentration { get; set; }
        public string Neatness { get; set; }
        public string Comportment { get; set; }
        public string Relation_with_Peer { get; set; }
        public string Obedience { get; set; }
        public string Punctuality { get; set; }
        public string Remark_Psycomotor { get; set; }
        public string Position { get; set; }
        public string Date_Vacation { get; set; }
        public string Date_Resumption { get; set; }
        public string Date { get; set; }
        public string School { get; set; }
        public System.DateTime L_U { get; set; }
    }
}
