//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_p_p1
    {
        public int p_id { get; set; }
        public string school { get; set; }
        public string name_student { get; set; }
        public string session { get; set; }
        public string term { get; set; }
        public string code { get; set; }
        public System.DateTime date { get; set; }
        public string g_school { get; set; }
    }
}
