//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_student_user
    {
        public int p_id { get; set; }
        public string Student_Name { get; set; }
        public string User_Name { get; set; }
        public string password { get; set; }
        public string school { get; set; }
        public System.DateTime L_U { get; set; }
    }
}
