//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_expenditure
    {
        public int p_id { get; set; }
        public string Expenses { get; set; }
        public decimal Amount { get; set; }
        public string Note { get; set; }
        public string code { get; set; }
        public string Date { get; set; }
        public string Day { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Registered_By { get; set; }
        public string Voucher_No { get; set; }
        public string School { get; set; }
        public string Item_Code { get; set; }
        public string Session { get; set; }
        public string Term { get; set; }
        public System.DateTime L_U { get; set; }
    }
}
