//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_SCONET_MANAGEMENT
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_exam
    {
        public int p_id { get; set; }
        public int Question_Number { get; set; }
        public string Subject { get; set; }
        public string Subject_Code { get; set; }
        public string Question { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        public string Answer { get; set; }
        public string Date { get; set; }
        public string Student_Name { get; set; }
        public string Time_Allowed { get; set; }
        public string Session { get; set; }
        public string Term { get; set; }
        public string Class { get; set; }
        public string Choice { get; set; }
        public string Code { get; set; }
        public string Url { get; set; }
        public string school { get; set; }
        public System.DateTime L_U { get; set; }
    }
}
